<a href="https://colab.research.google.com/github/prabhkaur301/ML-notebooks/blob/main/Social_Media_Content.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from pandas.core.common import random_state
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier

In [3]:
tds = pd.read_csv("/content/drive/MyDrive/Major project/True.csv")
fds = pd.read_csv("/content/drive/MyDrive/Major project/Fake.csv")

In [4]:
tds

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [5]:
class_true = ["Real"]*21417
tds["class_label"] = class_true
tds

,title,text,subject,date,class_label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",Real
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",Real
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",Real
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",Real
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",Real
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",Real
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",Real
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",Real
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",Real
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",Real

In [6]:
fds

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [7]:
class_fake = ["Fake"]*23481
fds["class_label"] = class_fake
fds

,title,text,subject,date,class_label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",Fake
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",Fake
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",Fake
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",Fake
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",Fake
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",Fake
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",Fake
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",Fake
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",Fake
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",Fake

In [8]:
tweets_dataset = pd.concat([tds,fds], axis=0)
tweets_dataset = tweets_dataset.sample(frac=1)#shuffled dataset
tweets_dataset.reset_index(inplace=True)
tweets_dataset

,index,title,text,subject,date,class_label
0,9613,BOOM! PRESIDENT TRUMP’S National Park Service ...,Beyonce made an attempt to glorify the violent...,politics,"Oct 24, 2017",Fake
1,15350,THE SECRET BEHIND AMERICA’S LOVE AFFAIR WITH T...,Every GOP Presidential candidate is racing to ...,politics,"Aug 8, 2015",Fake
2,8047,Most Clinton emails to be released after elect...,WASHINGTON (Reuters) - Most of the emails the ...,politicsNews,"September 23, 2016",Real
3,21320,HILLARY LIES: Remember When Hillary Disclosed ...,This story is from 2006 and is the first in a ...,left-news,"Nov 18, 2015",Fake
4,1989,EPA inspector general to investigate agency ch...,WASHINGTON/NEW YORK (Reuters) - The frequent t...,politicsNews,"August 28, 2017",Real
...,...,...,...,...,...,...
44893,2355,"Trump Tweets A Douchey, Self-congratulatory “...","On Wednesday, Donald Trump kicked off his morn...",News,"March 1, 2017",Fake
44894,16492,ALL WHITES IN BACK…Democrats Prove Their Obses...,Nothing says embracing diversity like dividing...,Government News,"Jul 22, 2016",Fake
44895,7046,Sanders to Trump: use defense contracts as lev...,"WEST PALM BEACH, Fla. (Reuters) - U.S. Senator...",politicsNews,"November 26, 2016",Real
44896,7202,Minnesota Republican: Gay People Are Mentally...,He probably believes pray the gay away is th...,News,"March 30, 2016",Fake
44897,10603,Obama adviser Deese to lead White House's Supr...,WASHINGTON (Reuters) - President Barack Obama ...,politicsNews,"February 29, 2016",Real

In [9]:
tweets_dataset.class_label.value_counts()

Fake    23481
Real    21417
Name: class_label, dtype: int64

In [10]:
tweets_dataset["class_label_num"] = tweets_dataset["class_label"].map({"Fake":0,"Real":1})
tweets_dataset

,index,title,text,subject,date,class_label,class_label_num
0,9613,BOOM! PRESIDENT TRUMP’S National Park Service ...,Beyonce made an attempt to glorify the violent...,politics,"Oct 24, 2017",Fake,0
1,15350,THE SECRET BEHIND AMERICA’S LOVE AFFAIR WITH T...,Every GOP Presidential candidate is racing to ...,politics,"Aug 8, 2015",Fake,0
2,8047,Most Clinton emails to be released after elect...,WASHINGTON (Reuters) - Most of the emails the ...,politicsNews,"September 23, 2016",Real,1
3,21320,HILLARY LIES: Remember When Hillary Disclosed ...,This story is from 2006 and is the first in a ...,left-news,"Nov 18, 2015",Fake,0
4,1989,EPA inspector general to investigate agency ch...,WASHINGTON/NEW YORK (Reuters) - The frequent t...,politicsNews,"August 28, 2017",Real,1
...,...,...,...,...,...,...,...
44893,2355,"Trump Tweets A Douchey, Self-congratulatory “...","On Wednesday, Donald Trump kicked off his morn...",News,"March 1, 2017",Fake,0
44894,16492,ALL WHITES IN BACK…Democrats Prove Their Obses...,Nothing says embracing diversity like dividing...,Government News,"Jul 22, 2016",Fake,0
44895,7046,Sanders to Trump: use defense contracts as lev...,"WEST PALM BEACH, Fla. (Reuters) - U.S. Senator...",politicsNews,"November 26, 2016",Real,1
44896,7202,Minnesota Republican: Gay People Are Mentally...,He probably believes pray the gay away is th...,News,"March 30, 2016",Fake,0
44897,10603,Obama adviser Deese to lead White House's Supr...,WASHINGTON (Reuters) - President Barack Obama ...,politicsNews,"February 29, 2016",Real,1

In [11]:
#pip install spacy

In [12]:
import spacy
spacy.cli.download("en_core_web_lg")
nlp = spacy.load("en_core_web_lg")

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [13]:
nlp("Rohit Sharma's Team India will face Jos Buttler-led England in the second semifinal of the ICC men’s T20 World Cup 2022 at the Adelaide Oval on Thursday (November 10).\n Fans are hoping for a India vs Pakistan final, with Babar Azam's side already in the final after win over New Zealand on Wednesday (November 9). \nRohit Sharma’s side topped Super 12 Group 2 table with four wins in five games, their only loss coming against South Africa at Perth.\n\nEngland, on the other hand, finished second in Super 12 Group 1, losing to Ireland and their game against Australia was washed out without a ball being bowled.").vector

array([-2.3039823e+00, -4.8331606e-01, -4.2694498e-02,  1.6287639e+00,
        5.0988216e+00,  6.1249471e-01, -2.0859660e-01,  3.7660935e+00,
        1.6424261e+00, -7.3296952e-01,  3.7434633e+00,  1.3188455e+00,
       -2.6714573e+00,  5.8924103e-01,  6.4309603e-01,  2.4375713e+00,
        3.2134494e-01,  7.4893558e-01,  4.5623758e-01, -1.6407700e+00,
        1.7550408e+00, -1.4433776e+00, -4.9194393e-01,  1.2070057e+00,
        9.7799733e-02, -7.4845541e-01, -3.1586130e+00, -7.8328413e-01,
        1.3847593e+00,  9.0497833e-01,  1.0825591e+00,  2.8411576e-01,
        3.7938085e-01, -3.4781389e+00, -2.1518216e+00, -1.2041390e+00,
       -1.1926230e+00,  1.0731066e+00, -1.3190188e+00, -9.9644047e-01,
        9.7590107e-01,  1.0205563e+00, -3.2839841e-01,  1.5045974e-01,
       -4.7012225e-01,  1.2236456e+00, -6.2082794e-02,  1.2873414e-01,
        1.7404875e-01,  3.1003368e-01, -5.1582485e-01,  1.6206520e+00,
       -1.2368802e+00, -2.1724801e+00, -7.1993157e-02,  2.2690172e+00,
       -1.4853113e+00,  2.3931332e-01,  5.6132478e-01, -2.6223864e-02,
       -1.8025846e+00, -4.4738650e-01, -6.4428067e-01,  5.4109019e-01,
        2.1580081e+00,  6.6165721e-01, -1.7210213e+00, -1.3142987e+00,
        3.1042993e-01,  1.3485529e+00,  5.4684961e-01, -6.4454395e-01,
       -1.4741184e+00,  7.2165537e-01,  4.7364004e-02,  4.4649303e-01,
       -4.9447924e-01,  1.8037968e+00, -1.7417444e+00,  7.9011977e-01,
       -2.4008017e+00, -9.2258513e-01, -1.4732240e+00,  5.5216628e-01,
        1.7983762e+00, -1.3056479e+00, -1.2964630e+00, -2.8472221e+00,
       -1.0551649e+00, -6.0228264e-01, -1.8216521e+00,  3.5072377e-01,
        4.5621362e-01, -8.9835072e-01,  1.4447387e-01,  1.5054226e-01,
       -4.7881044e-02, -2.0435462e+00,  1.5304615e+00,  1.5530117e+00,
        1.7093378e+00, -2.1232408e-01,  1.9013835e+00,  3.6741729e+00,
        4.9178013e-01,  2.4558911e+00, -5.1712209e-01, -1.7513535e+00,
       -4.2113948e-01, -2.9084046e+00,  8.7841827e-01,  9.1223961e-01,
       -1.3441519e+00, -2.1906599e-01,  2.0001292e-01, -9.7858465e-01,
       -1.7925271e-01,  1.1313045e+00, -2.2433603e-01, -3.4445247e-01,
        5.7649612e-01, -2.4951186e+00,  1.8515158e+00, -9.2640287e-01,
       -4.9878561e-01, -1.0357119e+00,  8.4159636e-01, -1.5103287e+00,
        3.1692002e+00, -1.5409266e+00, -2.0442698e+00, -5.4335356e-01,
        3.6948268e+00,  6.3541597e-01,  8.7635577e-01,  1.6599609e-01,
       -1.0063009e+00,  1.5420644e+00,  8.0478990e-01, -1.0725129e+00,
        2.7449942e-01,  5.1501743e-02, -3.7634808e-01,  9.5138901e-01,
        9.6665049e-01,  2.3698099e+00, -3.5799410e+00, -1.2591873e+00,
        2.7951024e+00,  1.5295948e+00, -2.0100053e-02,  1.0031997e+00,
        3.8327646e-01,  6.1434276e-02, -6.0920572e-01, -1.7770137e-01,
        2.1417096e+00, -6.7306250e-01, -6.0939664e-01, -1.9368520e+00,
       -7.2973973e-01, -2.2651396e+00,  1.6142484e+00,  2.2650402e+00,
       -1.4793705e+00,  2.0303419e-01, -1.4730366e+00,  4.9627791e-03,
        8.0348444e-01,  2.3881824e+00,  2.9015973e-02,  7.0468599e-01,
        6.7143971e-01,  4.6568234e-02,  3.4954897e-01,  2.0005662e+00,
       -1.1451938e+00, -4.0800261e-01, -2.7824962e+00, -7.4474251e-01,
       -1.0838237e+00,  4.5553410e-01, -3.7134227e-01,  4.3880892e-01,
       -2.1171823e+00,  2.1038425e+00, -8.6575341e-01,  1.2115134e+00,
        1.2390400e-01,  2.5226906e-01,  6.6982859e-01, -9.2113906e-01,
        5.5095226e-01, -2.8068912e+00,  1.7310921e+00,  4.9284986e-01,
       -1.3801922e+00, -5.2743798e-01, -4.6926403e-01, -1.6243674e-01,
       -1.2228164e-01, -1.7255173e+00,  9.1121727e-01, -3.4749007e+00,
        3.6557019e+00, -1.6986422e-01, -2.8471570e+00,  2.3077955e+00,
       -9.0928745e-01,  1.0207993e+00,  8.0895948e-01,  1.1174045e+00,
       -6.7146957e-01,  1.7348609e+00,  2.1830292e+00,  2.2962911e+00,
       -3.1144020e-01, -1.6847075e+00, -8.7252963e-01, -1.1530941e+00,
       -1.8063942e+00,  1.1287596e+00, -4.1016087e-01, -2.9808608e-01,
       -3.0836210e+00, -2.1487269e+00, -2.2259805e-01,  2.2072492e+00,
        9.3560731e-01,  1.9199525e-01,  2.3965399e+00, -1.7655889e+00,
        3.1718189e-01,  1.8783027e+00,  1.9067575e+00,  1.3726002e+00,
       -6.1773813e-01, -4.1443565e-01, -1.6731254e+00, -8.6288458e-01,
       -2.0884754e-02, -1.9952443e-01,  1.0098281e-02,  7.0209908e-01,
       -1.0849098e+00,  8.6219370e-01, -4.4334048e-01,  5.9681451e-01,
       -4.5360184e-01,  2.0574622e+00,  6.4257199e-01, -2.3237472e+00,
       -3.3398499e+00,  1.4608234e+00,  1.0707270e+00, -7.7058631e-01,
        2.0681322e+00, -4.6811554e-01,  1.9106897e+00,  1.5053505e+00,
       -3.4402558e-01,  2.5646777e+00,  1.8192555e+00,  1.2975110e+00,
        1.3228317e+00, -9.9391472e-01, -3.3396083e-01,  1.3599783e+00,
       -1.4951165e+00,  1.0444878e-01,  5.9977502e-01, -2.5155589e-01,
        1.4207829e+00, -1.4447153e+00,  6.4472699e-01,  3.1379190e-01,
        1.0739256e+00, -9.7889918e-01,  8.0926603e-01,  1.0831453e+00,
        2.8548896e+00,  6.0871714e-01,  5.1878977e-01,  6.7022061e-01,
        1.1826584e+00,  2.0625612e-01, -8.4040391e-01,  3.3923632e-01,
       -1.1206084e+00, -5.8370084e-01,  3.7224936e-01, -4.6535024e-01,
       -1.5948808e+00,  8.1352615e-01, -1.0379322e+00,  1.6846545e+00,
        1.1032021e+00, -2.9240599e+00, -4.2938590e-01,  6.0264927e-01],
      dtype=float32)

In [ ]:
tweets_dataset["text_vec"]=tweets_dataset["text"].apply(lambda text: nlp(text).vector)
tweets_dataset

In [ ]:
#tweets_dataset.to_csv("/content/drive/MyDrive/Fake_News_Detection/TweetsDataset.csv", index=False)
#tweetdata = pd.read_csv("/content/drive/MyDrive/Fake_News_Detection/TweetsDataset.csv")
#tweetdata

In [ ]:
tweet_train, tweet_test, label_train, label_test = train_test_split(tweets_dataset.text_vec.values, tweets_dataset.class_label_num, test_size=0.2, random_state=2022)

In [ ]:
tweet_train_2D = np.stack(tweet_train)
tweet_test_2D = np.stack(tweet_test)

In [ ]:
"""
https://www.researchgate.net/post/what_are_the_different_algorithms_for_text_classification

Some Traditional ML Algorithms:
Logisitic Regression, Multinomial Naive Bayes, k Nearest Neighbors, Decision Tree and Support Vector Machine
Some Ensemble ML Algorithms are:
Adaboost, Random Forest, Bagging, Gradient Boosting etc
deep learning ones: 
Convolutional Neural Network (CNN), Long Short Term Modelr (LSTM), Recurrent Convolutional Neural Network (RCNN), etc
"""

In [ ]:
mnb = MultinomialNB()
scaler = MinMaxScaler()
scaled_train = scaler.fit_transform(tweet_train_2D) #Negative values in data passed to MultinomialNB (input X)
scaled_test = scaler.transform(tweet_test_2D)
mnb.fit(scaled_train, label_train) # scaled to get positive range of numbers for pos & neg data

In [ ]:
label_pred = mnb.predict(scaled_test)
print(classification_report(label_test, label_pred))

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 5, metric = "euclidean")
knn.fit(tweet_train_2D, label_train)

In [ ]:
label_pred_knn = knn.predict(tweet_test_2D)
print(classification_report(label_test, label_pred_knn))

In [ ]:
#lr = LogisticRegression()
#lr.fit(tweet_train_2D, label_train) #ConvergenceWarning: lbfgs failed to converge (status=1): STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

In [ ]:
sv = svm.SVC()
sv.fit(tweet_train_2D, label_train)

In [ ]:
label_pred_sv = sv.predict(tweet_test_2D)
print(classification_report(label_test, label_pred_sv))

In [ ]:
randfor = RandomForestClassifier(max_depth=14, random_state=2022) # at max_depth 14, acc is max, no inc after that
#The random_state in these algorithms controls two randomized processes — bootstrapping of the samples when creating tress and getting a random subset of features to search for the best feature during the node splitting process when creating each tree.
randfor.fit(tweet_train_2D, label_train)

In [ ]:
label_pred_randfor = randfor.predict(tweet_test_2D)
print(classification_report(label_test, label_pred_randfor))